# cloudbuild for cloud functions

steps:
  # install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: functions

  # build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: functions

  # deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - deploy
      - --only=functions
