# cloudbuild for TMD

steps:
  # decrypt keys
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env.local
      - --location=global
      - --keyring=TMD
      - --key=cloudbuild-env

  # install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # # runs tests
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['run', 'test']

  # build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'VITE_IS_LIVE=true'

  # build docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', './']

  # docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  # Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NAME',
        '--image',
        'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
        '--region',
        '$_DEPLOY_REGION',
      ]
    entrypoint: gcloud

  # deploy project to firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - deploy
      - --only=hosting

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
